default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: burnbox

test: &test
  <<: *default
  database: burnbox_test

production:
  <<: *default
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>

cucumber:
  <<: *test
